name: Weekly CI
on:
  schedule:
    - cron: "0 0 * * 1"
  repository_dispatch:
    types: [weekly]
jobs:
  release:
    name: Weekly
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run script
        run: npm run weekly
        env:
          GOODREADS_USER_ID: ${{ secrets.GOODREADS_USER_ID }}
          GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
          GOODREADS_SECRET: ${{ secrets.GOODREADS_SECRET }}
          GOODREADS_CALLBACK_URL: ${{ secrets.GOODREADS_CALLBACK_URL }}
          POCKET_CASTS_USERNAME: ${{ secrets.POCKET_CASTS_USERNAME }}
          POCKET_CASTS_PASSWORD: ${{ secrets.POCKET_CASTS_PASSWORD }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_CALLBACK_URL: ${{ secrets.SPOTIFY_CALLBACK_URL }}
          SPOTIFY_ACCESS_TOKEN: ${{ secrets.SPOTIFY_ACCESS_TOKEN }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      - name: Commit new data
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: ":card_file_box: Update weekly life data [skip ci]"
          commit_user_name: Finding Anand
          commit_user_email: bot@anandchowdhary.com
          commit_author: Finding Anand <bot@anandchowdhary.com>
